name: FastAPI Deployment on Windows

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: windows-latest  # Change runner to Windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pandas scikit-learn

      - name: Run FastAPI Server
        run: |
          start /B uvicorn api:app --host 0.0.0.0 --port 8000
          timeout /T 99999  # Prevents auto-stop
