name: FastAPI Deployment on Windows

on:
  push:
    branches:
      - master  # Ensure it matches your branch name

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pandas scikit-learn

      - name: Run FastAPI Server
        run: |
          uvicorn api:app --host 0.0.0.0 --port 8000 &
          echo "API is running at: http://127.0.0.1:8000/docs"
